/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otrointento;

import Data.XMLCarreraManager;
import threads.Carrera;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import Domain.auto;
import java.io.IOException;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;
import org.jdom.JDOMException;
import threads.Carrera1;
import threads.Carrera2;
import threads.CarreraB;
import threads.CarreraB1;
import threads.CarreraB2;
import threads.CarreraR;
import threads.CarreraR1;
import threads.CarreraR2;

/**
 *
 * @author Rita
 */
public class frmauto extends javax.swing.JFrame  {
   

    boolean parar = false;
    int time = 100, time2 = 250, time3 = 50, f = 1;


    
    /**
     * Creates new form frmauto
     */
    public frmauto() {
        initComponents();
    }

    public JLabel getLabel1() {
        return Label1;
    }

    public JLabel getLabel2() {
        return Label2;
    }

    public JLabel getLabel3() {
        return jLabel7;
    }

    public JLabel getLabelLinea() {
        return LabelLinea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        LabelLinea = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ButtonIniciar = new javax.swing.JButton();
        ButtonBarrier = new javax.swing.JButton();
        Restart = new javax.swing.JButton();
        Checkbox = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ButtonRevert = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Interrupt = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label1.setIcon(new javax.swing.ImageIcon("E:\\imagenesp\\Car_Right_Red_26350.png")); // NOI18N
        jPanel1.add(Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        Label2.setIcon(new javax.swing.ImageIcon("E:\\imagenesp\\Car_Right_Red_26350.png")); // NOI18N
        jPanel1.add(Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));
        jPanel1.add(LabelLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, -4, -1, 360));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\imagenesp\\Car_Right_Red_26350.png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\imagenesp\\pistaDefinitiva.jpeg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 810, -1));

        jLabel1.setText("Carrera De Autos");

        ButtonIniciar.setText("Iniciar Carrera");
        ButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIniciarActionPerformed(evt);
            }
        });

        ButtonBarrier.setText("Barrier");
        ButtonBarrier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBarrierActionPerformed(evt);
            }
        });

        Restart.setText("Restart");
        Restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartActionPerformed(evt);
            }
        });

        Checkbox.setText("Imagenes");
        Checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckboxActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton2.setText("Simulation");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ButtonRevert.setText("Revert");
        ButtonRevert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRevertActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "1, 2", "1, 3", "2, 3", "1, 2, 3", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Ingrese la velocidad para cada auto (1,2,3)");

        jLabel9.setText("Auto 1");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel10.setText("Auto 2");

        jLabel11.setText("Auto 3");

        Interrupt.setIcon(new javax.swing.ImageIcon("E:\\OtroIntento\\src\\otrointento\\player-play-button-of-circular-shape.png")); // NOI18N
        Interrupt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InterruptActionPerformed(evt);
            }
        });

        jLabel12.setText("Carriles que en los que se activará la barrera ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonIniciar)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Checkbox)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonBarrier)
                                .addGap(40, 40, 40)
                                .addComponent(ButtonRevert))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(316, 316, 316))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(165, 165, 165)
                                                .addComponent(jLabel3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel9)
                                                .addGap(149, 149, 149)
                                                .addComponent(jButton2)
                                                .addGap(18, 18, 18)
                                                .addComponent(Restart)
                                                .addGap(60, 60, 60)
                                                .addComponent(Interrupt))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(220, 220, 220))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ButtonIniciar)
                                    .addComponent(Checkbox))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton2)
                                            .addComponent(Restart)
                                            .addComponent(ButtonBarrier)
                                            .addComponent(ButtonRevert))
                                        .addGap(23, 23, 23))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Interrupt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)))))
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)))))
                .addGap(28, 28, 28))
        );

        jComboBox1.getAccessibleContext().setAccessibleParent(jComboBox1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIniciarActionPerformed
        try {
            // TODO add your handling code here:
            XMLCarreraManager xmlcm= new XMLCarreraManager("./Data/auto.xml");
            xmlcm.insertCarrea(this);
        } catch (IOException ex) {
            Logger.getLogger(frmauto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JDOMException ex) {
            Logger.getLogger(frmauto.class.getName()).log(Level.SEVERE, null, ex);
        }
        Label1.setLocation(Label1.getLocation().x, Label1.getLocation().y);
        Label2.setLocation(Label2.getLocation().x, Label2.getLocation().y);
        jLabel7.setLocation(jLabel7.getLocation().x, jLabel7.getLocation().y);

        if (jTextField2.getText().equalsIgnoreCase("1") || jTextField2.getText().equalsIgnoreCase("bajo")) {
            Carrera2 hilo3 = new Carrera2(jLabel7, this, time2);
            hilo3.start();
        } else if (jTextField2.getText().equalsIgnoreCase("2") || jTextField2.getText().equalsIgnoreCase("medio")) {
            Carrera2 hilo3 = new Carrera2(jLabel7, this, time);
            hilo3.start();
        } else if (jTextField2.getText().equalsIgnoreCase("3") || jTextField2.getText().equalsIgnoreCase("rapido")) {
            Carrera2 hilo3 = new Carrera2(jLabel7, this, time3);
            hilo3.start();
        } else {
            jLabel4.setText("velocidad incorrecta");
        }
        jTextField2.setText("");

        if (jTextField3.getText().equalsIgnoreCase("1") || jTextField3.getText().equalsIgnoreCase("bajo")) {
            Carrera1 hilo2 = new Carrera1(Label1, this, time2);
            hilo2.start();
        } else if (jTextField3.getText().equalsIgnoreCase("2") || jTextField3.getText().equalsIgnoreCase("medio")) {
            Carrera1 hilo2 = new Carrera1(Label1, this, time);
            hilo2.start();
        } else if (jTextField3.getText().equalsIgnoreCase("3") || jTextField3.getText().equalsIgnoreCase("rapido")) {
            Carrera1 hilo2 = new Carrera1(Label1, this, time3);
            hilo2.start();
        } else {
            jLabel4.setText("velocidad incorrecta");
        }
        jTextField3.setText("");
        if (jTextField4.getText().equalsIgnoreCase("1") || jTextField4.getText().equalsIgnoreCase("bajo")) {
            Carrera hilo1 = new Carrera(Label2, this, time2);
            hilo1.start();
        } else if (jTextField4.getText().equalsIgnoreCase("2") || jTextField4.getText().equalsIgnoreCase("medio")) {
            Carrera hilo1 = new Carrera(Label2, this, time);
            hilo1.start();
        } else if (jTextField4.getText().equalsIgnoreCase("3") || jTextField4.getText().equalsIgnoreCase("rapido")) {

            Carrera hilo1 = new Carrera(Label2, this, time3);
            hilo1.start();

        } else {
            jLabel4.setText("velocidad incorrecta");
        }
        jTextField4.setText("");

    }//GEN-LAST:event_ButtonIniciarActionPerformed

    private void ButtonBarrierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBarrierActionPerformed
        //if(f==1){
        Label1.setLocation(Label1.getLocation().x, Label1.getLocation().y);
        Label2.setLocation(Label2.getLocation().x, Label2.getLocation().y);
        jLabel7.setLocation(jLabel7.getLocation().x, jLabel7.getLocation().y);
        if (ButtonBarrier.isEnabled()) {
            jLabel8.setIcon(new ImageIcon(getClass().getResource("barrera.jpeg")));

            if (jComboBox1.getSelectedItem().equals("1")) {

                if (jTextField2.getText().equalsIgnoreCase("1") || jTextField2.getText().equalsIgnoreCase("bajo")) {
                    CarreraB2 hilo3 = new CarreraB2(jLabel7, this, time2);
                    hilo3.start();
                } else if (jTextField2.getText().equalsIgnoreCase("2") || jTextField2.getText().equalsIgnoreCase("medio")) {
                    CarreraB2 hilo3 = new CarreraB2(jLabel7, this, time);
                    hilo3.start();
                } else if (jTextField2.getText().equalsIgnoreCase("3") || jTextField2.getText().equalsIgnoreCase("rapido")) {
                    CarreraB2 hilo3 = new CarreraB2(jLabel7, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField2.setText("");

                if (jTextField3.getText().equalsIgnoreCase("1") || jTextField3.getText().equalsIgnoreCase("bajo")) {
                    Carrera1 hilo3 = new Carrera1(Label1, this, time2);
                    hilo3.start();
                } else if (jTextField3.getText().equalsIgnoreCase("2") || jTextField3.getText().equalsIgnoreCase("medio")) {
                    Carrera1 hilo3 = new Carrera1(Label1, this, time);
                    hilo3.start();
                } else if (jTextField3.getText().equalsIgnoreCase("3") || jTextField3.getText().equalsIgnoreCase("rapido")) {
                    Carrera1 hilo3 = new Carrera1(Label1, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField3.setText("");

                if (jTextField4.getText().equalsIgnoreCase("1") || jTextField4.getText().equalsIgnoreCase("bajo")) {
                    Carrera hilo3 = new Carrera(Label2, this, time2);
                    hilo3.start();
                } else if (jTextField4.getText().equalsIgnoreCase("2") || jTextField4.getText().equalsIgnoreCase("medio")) {
                    Carrera hilo3 = new Carrera(Label2, this, time);
                    hilo3.start();
                } else if (jTextField4.getText().equalsIgnoreCase("3") || jTextField4.getText().equalsIgnoreCase("rapido")) {
                    Carrera hilo3 = new Carrera(Label2, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField4.setText("");

            }
            if (jComboBox1.getSelectedItem().equals("2")) {
                if (jTextField2.getText().equalsIgnoreCase("1") || jTextField2.getText().equalsIgnoreCase("bajo")) {
                    Carrera2 hilo3 = new Carrera2(jLabel7, this, time2);
                    hilo3.start();
                } else if (jTextField2.getText().equalsIgnoreCase("2") || jTextField2.getText().equalsIgnoreCase("medio")) {
                    Carrera2 hilo3 = new Carrera2(jLabel7, this, time);
                    hilo3.start();
                } else if (jTextField2.getText().equalsIgnoreCase("3") || jTextField2.getText().equalsIgnoreCase("rapido")) {
                    Carrera2 hilo3 = new Carrera2(jLabel7, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField2.setText("");

                if (jTextField3.getText().equalsIgnoreCase("1") || jTextField3.getText().equalsIgnoreCase("bajo")) {
                    CarreraB1 hilo3 = new CarreraB1(Label1, this, time2);
                    hilo3.start();
                } else if (jTextField3.getText().equalsIgnoreCase("2") || jTextField3.getText().equalsIgnoreCase("medio")) {
                    CarreraB1 hilo3 = new CarreraB1(Label1, this, time);
                    hilo3.start();
                } else if (jTextField3.getText().equalsIgnoreCase("3") || jTextField3.getText().equalsIgnoreCase("rapido")) {
                    CarreraB1 hilo3 = new CarreraB1(Label1, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField3.setText("");

                if (jTextField4.getText().equalsIgnoreCase("1") || jTextField4.getText().equalsIgnoreCase("bajo")) {
                    Carrera hilo3 = new Carrera(Label2, this, time2);
                    hilo3.start();
                } else if (jTextField4.getText().equalsIgnoreCase("2") || jTextField4.getText().equalsIgnoreCase("medio")) {
                    Carrera hilo3 = new Carrera(Label2, this, time);
                    hilo3.start();
                } else if (jTextField4.getText().equalsIgnoreCase("3") || jTextField4.getText().equalsIgnoreCase("rapido")) {
                    Carrera hilo3 = new Carrera(Label2, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField4.setText("");

            }
            if (jComboBox1.getSelectedItem().equals("3")) {
                if (jTextField2.getText().equalsIgnoreCase("1") || jTextField2.getText().equalsIgnoreCase("bajo")) {
                    Carrera2 hilo3 = new Carrera2(jLabel7, this, time2);
                    hilo3.start();
                } else if (jTextField2.getText().equalsIgnoreCase("2") || jTextField2.getText().equalsIgnoreCase("medio")) {
                    Carrera2 hilo3 = new Carrera2(jLabel7, this, time);
                    hilo3.start();
                } else if (jTextField2.getText().equalsIgnoreCase("3") || jTextField2.getText().equalsIgnoreCase("rapido")) {
                    Carrera2 hilo3 = new Carrera2(jLabel7, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField2.setText("");

                if (jTextField3.getText().equalsIgnoreCase("1") || jTextField3.getText().equalsIgnoreCase("bajo")) {
                    Carrera1 hilo3 = new Carrera1(Label1, this, time2);
                    hilo3.start();
                } else if (jTextField3.getText().equalsIgnoreCase("2") || jTextField3.getText().equalsIgnoreCase("medio")) {
                    Carrera1 hilo3 = new Carrera1(Label1, this, time);
                    hilo3.start();
                } else if (jTextField3.getText().equalsIgnoreCase("3") || jTextField3.getText().equalsIgnoreCase("rapido")) {
                    Carrera1 hilo3 = new Carrera1(Label1, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField3.setText("");

                if (jTextField4.getText().equalsIgnoreCase("1") || jTextField4.getText().equalsIgnoreCase("bajo")) {
                    CarreraB hilo3 = new CarreraB(Label2, this, time2);
                    hilo3.start();
                } else if (jTextField4.getText().equalsIgnoreCase("2") || jTextField4.getText().equalsIgnoreCase("medio")) {
                    CarreraB hilo3 = new CarreraB(Label2, this, time);
                    hilo3.start();
                } else if (jTextField4.getText().equalsIgnoreCase("3") || jTextField4.getText().equalsIgnoreCase("rapido")) {
                    CarreraB hilo3 = new CarreraB(Label2, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField4.setText("");

            }

            if (jComboBox1.getSelectedItem().equals("1, 2")) {
                if (jTextField2.getText().equalsIgnoreCase("1") || jTextField2.getText().equalsIgnoreCase("bajo")) {
                    CarreraB2 hilo3 = new CarreraB2(jLabel7, this, time2);
                    hilo3.start();
                } else if (jTextField2.getText().equalsIgnoreCase("2") || jTextField2.getText().equalsIgnoreCase("medio")) {
                    CarreraB2 hilo3 = new CarreraB2(jLabel7, this, time);
                    hilo3.start();
                } else if (jTextField2.getText().equalsIgnoreCase("3") || jTextField2.getText().equalsIgnoreCase("rapido")) {
                    CarreraB2 hilo3 = new CarreraB2(jLabel7, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField2.setText("");

                if (jTextField3.getText().equalsIgnoreCase("1") || jTextField3.getText().equalsIgnoreCase("bajo")) {
                    CarreraB1 hilo3 = new CarreraB1(Label1, this, time2);
                    hilo3.start();
                } else if (jTextField3.getText().equalsIgnoreCase("2") || jTextField3.getText().equalsIgnoreCase("medio")) {
                    CarreraB1 hilo3 = new CarreraB1(Label1, this, time);
                    hilo3.start();
                } else if (jTextField3.getText().equalsIgnoreCase("3") || jTextField3.getText().equalsIgnoreCase("rapido")) {
                    CarreraB1 hilo3 = new CarreraB1(Label1, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField3.setText("");

                if (jTextField4.getText().equalsIgnoreCase("1") || jTextField4.getText().equalsIgnoreCase("bajo")) {
                    Carrera hilo3 = new Carrera(Label2, this, time2);
                    hilo3.start();
                } else if (jTextField4.getText().equalsIgnoreCase("2") || jTextField4.getText().equalsIgnoreCase("medio")) {
                    Carrera hilo3 = new Carrera(Label2, this, time);
                    hilo3.start();
                } else if (jTextField4.getText().equalsIgnoreCase("3") || jTextField4.getText().equalsIgnoreCase("rapido")) {
                    Carrera hilo3 = new Carrera(Label2, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField4.setText("");

            }

            if (jComboBox1.getSelectedItem().equals("1, 3")) {
                if (jTextField2.getText().equalsIgnoreCase("1") || jTextField2.getText().equalsIgnoreCase("bajo")) {
                    CarreraB2 hilo3 = new CarreraB2(jLabel7, this, time2);
                    hilo3.start();
                } else if (jTextField2.getText().equalsIgnoreCase("2") || jTextField2.getText().equalsIgnoreCase("medio")) {
                    CarreraB2 hilo3 = new CarreraB2(jLabel7, this, time);
                    hilo3.start();
                } else if (jTextField2.getText().equalsIgnoreCase("3") || jTextField2.getText().equalsIgnoreCase("rapido")) {
                    CarreraB2 hilo3 = new CarreraB2(jLabel7, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField2.setText("");

                if (jTextField3.getText().equalsIgnoreCase("1") || jTextField3.getText().equalsIgnoreCase("bajo")) {
                    Carrera1 hilo3 = new Carrera1(Label1, this, time2);
                    hilo3.start();
                } else if (jTextField3.getText().equalsIgnoreCase("2") || jTextField3.getText().equalsIgnoreCase("medio")) {
                    Carrera1 hilo3 = new Carrera1(Label1, this, time);
                    hilo3.start();
                } else if (jTextField3.getText().equalsIgnoreCase("3") || jTextField3.getText().equalsIgnoreCase("rapido")) {
                    Carrera1 hilo3 = new Carrera1(Label1, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField3.setText("");

                if (jTextField4.getText().equalsIgnoreCase("1") || jTextField4.getText().equalsIgnoreCase("bajo")) {
                    CarreraB hilo3 = new CarreraB(Label2, this, time2);
                    hilo3.start();
                } else if (jTextField4.getText().equalsIgnoreCase("2") || jTextField4.getText().equalsIgnoreCase("medio")) {
                    CarreraB hilo3 = new CarreraB(Label2, this, time);
                    hilo3.start();
                } else if (jTextField4.getText().equalsIgnoreCase("3") || jTextField4.getText().equalsIgnoreCase("rapido")) {
                    CarreraB hilo3 = new CarreraB(Label2, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField4.setText("");

            }

            if (jComboBox1.getSelectedItem().equals("2, 3")) {
                if (jTextField2.getText().equalsIgnoreCase("1") || jTextField2.getText().equalsIgnoreCase("bajo")) {
                    Carrera2 hilo3 = new Carrera2(jLabel7, this, time2);
                    hilo3.start();
                } else if (jTextField2.getText().equalsIgnoreCase("2") || jTextField2.getText().equalsIgnoreCase("medio")) {
                    Carrera2 hilo3 = new Carrera2(jLabel7, this, time);
                    hilo3.start();
                } else if (jTextField2.getText().equalsIgnoreCase("3") || jTextField2.getText().equalsIgnoreCase("rapido")) {
                    Carrera2 hilo3 = new Carrera2(jLabel7, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField2.setText("");

                if (jTextField3.getText().equalsIgnoreCase("1") || jTextField3.getText().equalsIgnoreCase("bajo")) {
                    CarreraB1 hilo3 = new CarreraB1(Label1, this, time2);
                    hilo3.start();
                } else if (jTextField3.getText().equalsIgnoreCase("2") || jTextField3.getText().equalsIgnoreCase("medio")) {
                    CarreraB1 hilo3 = new CarreraB1(Label1, this, time);
                    hilo3.start();
                } else if (jTextField3.getText().equalsIgnoreCase("3") || jTextField3.getText().equalsIgnoreCase("rapido")) {
                    CarreraB1 hilo3 = new CarreraB1(Label1, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField3.setText("");

                if (jTextField4.getText().equalsIgnoreCase("1") || jTextField4.getText().equalsIgnoreCase("bajo")) {
                    CarreraB hilo3 = new CarreraB(Label2, this, time2);
                    hilo3.start();
                } else if (jTextField4.getText().equalsIgnoreCase("2") || jTextField4.getText().equalsIgnoreCase("medio")) {
                    CarreraB hilo3 = new CarreraB(Label2, this, time);
                    hilo3.start();
                } else if (jTextField4.getText().equalsIgnoreCase("3") || jTextField4.getText().equalsIgnoreCase("rapido")) {
                    CarreraB hilo3 = new CarreraB(Label2, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField4.setText("");

            }

            if (jComboBox1.getSelectedItem().equals("1, 2, 3")) {
                if (jTextField2.getText().equalsIgnoreCase("1") || jTextField2.getText().equalsIgnoreCase("bajo")) {
                    CarreraB2 hilo3 = new CarreraB2(jLabel7, this, time2);
                    hilo3.start();
                } else if (jTextField2.getText().equalsIgnoreCase("2") || jTextField2.getText().equalsIgnoreCase("medio")) {
                    CarreraB2 hilo3 = new CarreraB2(jLabel7, this, time);
                    hilo3.start();
                } else if (jTextField2.getText().equalsIgnoreCase("3") || jTextField2.getText().equalsIgnoreCase("rapido")) {
                    CarreraB2 hilo3 = new CarreraB2(jLabel7, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField2.setText("");

                if (jTextField3.getText().equalsIgnoreCase("1") || jTextField3.getText().equalsIgnoreCase("bajo")) {
                    CarreraB1 hilo3 = new CarreraB1(Label1, this, time2);
                    hilo3.start();
                } else if (jTextField3.getText().equalsIgnoreCase("2") || jTextField3.getText().equalsIgnoreCase("medio")) {
                    CarreraB1 hilo3 = new CarreraB1(Label1, this, time);
                    hilo3.start();
                } else if (jTextField3.getText().equalsIgnoreCase("3") || jTextField3.getText().equalsIgnoreCase("rapido")) {
                    CarreraB1 hilo3 = new CarreraB1(Label1, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField3.setText("");

                if (jTextField4.getText().equalsIgnoreCase("1") || jTextField4.getText().equalsIgnoreCase("bajo")) {
                    CarreraB hilo3 = new CarreraB(Label2, this, time2);
                    hilo3.start();
                } else if (jTextField4.getText().equalsIgnoreCase("2") || jTextField4.getText().equalsIgnoreCase("medio")) {
                    CarreraB hilo3 = new CarreraB(Label2, this, time);
                    hilo3.start();
                } else if (jTextField4.getText().equalsIgnoreCase("3") || jTextField4.getText().equalsIgnoreCase("rapido")) {
                    CarreraB hilo3 = new CarreraB(Label2, this, time3);
                    hilo3.start();
                } else {
                    jLabel4.setText("velocidad incorrecta");
                }
                jTextField4.setText("");
            }
        }
    }//GEN-LAST:event_ButtonBarrierActionPerformed

    private void RestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartActionPerformed

        if (Restart.isEnabled()) {
            Label1.setLocation(240, 320);
            Label2.setLocation(240, 360);
            jLabel7.setLocation(240, 280);
            jLabel8.setIcon(new ImageIcon(""));

        }
    }//GEN-LAST:event_RestartActionPerformed

    private void CheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckboxActionPerformed
        if (Checkbox.isSelected()) {
            Label1.setIcon(new ImageIcon(getClass().getResource("cuadrado.png")));
            Label2.setIcon(new ImageIcon(getClass().getResource("rombo.png")));
            jLabel7.setIcon(new ImageIcon(getClass().getResource("poligono.png")));
        } else {
            Label1.setIcon(new ImageIcon(getClass().getResource("carro.png")));
            Label2.setIcon(new ImageIcon(getClass().getResource("carro.png")));
            jLabel7.setIcon(new ImageIcon(getClass().getResource("carro.png")));
        }
    }//GEN-LAST:event_CheckboxActionPerformed

    private void ButtonRevertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRevertActionPerformed
        if (ButtonRevert.isEnabled()) {

            Label1.setIcon(new ImageIcon(getClass().getResource("carroR.png")));
            Label2.setIcon(new ImageIcon(getClass().getResource("carroR.png")));
            jLabel7.setIcon(new ImageIcon(getClass().getResource("carroR.png")));
        }
        Label2.setLocation(Label2.getLocation().x, Label2.getLocation().y);
        CarreraR hilo4 = new CarreraR(Label2, this, time);
        hilo4.start();

        Label1.setLocation(Label1.getLocation().x, Label1.getLocation().y);
        CarreraR1 hilo1 = new CarreraR1(Label1, this, time);
        hilo1.start();

        jLabel7.setLocation(jLabel7.getLocation().x, jLabel7.getLocation().y);
        CarreraR2 hilo2 = new CarreraR2(jLabel7, this, time);
        hilo2.start();
    }//GEN-LAST:event_ButtonRevertActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Label1.setLocation(Label1.getLocation().x, Label1.getLocation().y);
        Label2.setLocation(Label2.getLocation().x, Label2.getLocation().y);
        jLabel7.setLocation(jLabel7.getLocation().x, jLabel7.getLocation().y);
        int i = (int) (Math.random() * 3) + 1;
        int h = (int) (Math.random() * 3) + 1;
        int j = (int) (Math.random() * 3) + 1;
        if (i == 1) {
            Label2.setIcon(new ImageIcon(getClass().getResource("rombo.png")));
            Carrera hilo1 = new Carrera(Label2, this, time2);
            hilo1.start();
        }
        if (i == 2) {
            Carrera hilo1 = new Carrera(Label2, this, time);
            hilo1.start();
        }
        if (i == 3) {
            Label2.setIcon(new ImageIcon(getClass().getResource("rombo.png")));
            Carrera hilo1 = new Carrera(Label2, this, time3);
            hilo1.start();
        }

        if (h == 1) {
            Label1.setIcon(new ImageIcon(getClass().getResource("cuadrado.png")));
            Carrera1 hilo1 = new Carrera1(Label1, this, time2);
            hilo1.start();
        }
        if (h == 2) {
            Carrera1 hilo1 = new Carrera1(Label1, this, time);
            hilo1.start();
        }
        if (h == 3) {
            Label1.setIcon(new ImageIcon(getClass().getResource("cuadrado.png")));
            Carrera1 hilo1 = new Carrera1(Label1, this, time3);
            hilo1.start();
        }

        if (j == 1) {
            jLabel7.setIcon(new ImageIcon(getClass().getResource("poligono.png")));
            Carrera2 hilo1 = new Carrera2(jLabel7, this, time2);
            hilo1.start();
        }
        if (j == 2) {
            Carrera2 hilo1 = new Carrera2(jLabel7, this, time);
            hilo1.start();
        }
        if (j == 3) {
            jLabel7.setIcon(new ImageIcon(getClass().getResource("poligono.png")));
            Carrera1 hilo1 = new Carrera1(jLabel7, this, time3);
            hilo1.start();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void InterruptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InterruptActionPerformed
        // TODO add your handling code here:
        Carrera hilo1 = new Carrera(Label2, this, time);
        Carrera1 hilo2 = new Carrera1(Label1, this, time);
        Carrera2 hilo3 = new Carrera2(jLabel7, this, time);
        if (Interrupt.isEnabled()) {
            if (parar == true) {
                try {
                    parar = false;

                    hilo2.sleep(2000);
                    hilo3.sleep(2000);
                    hilo1.sleep(2000);


                } catch (InterruptedException ex) {
                    Logger.getLogger(frmauto.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                parar = true;

            }
        }
    }//GEN-LAST:event_InterruptActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmauto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmauto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmauto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmauto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmauto().setVisible(true);
            }
        });
    }

    public boolean isParar() {
        return parar;
    }

    public void setParar(boolean parar) {
        this.parar = parar;
    }

    public int getTime() {
        return time;
    }

    public void setTime(int time) {
        this.time = time;
    }

    public int getTime2() {
        return time2;
    }

    public void setTime2(int time2) {
        this.time2 = time2;
    }

    public int getTime3() {
        return time3;
    }

    public void setTime3(int time3) {
        this.time3 = time3;
    }

    public int getF() {
        return f;
    }

    public void setF(int f) {
        this.f = f;
    }

    public JButton getButtonBarrier() {
        return ButtonBarrier;
    }

    public void setButtonBarrier(JButton ButtonBarrier) {
        this.ButtonBarrier = ButtonBarrier;
    }

    public JButton getButtonIniciar() {
        return ButtonIniciar;
    }

    public void setButtonIniciar(JButton ButtonIniciar) {
        this.ButtonIniciar = ButtonIniciar;
    }

    public JButton getButtonRevert() {
        return ButtonRevert;
    }

    public void setButtonRevert(JButton ButtonRevert) {
        this.ButtonRevert = ButtonRevert;
    }

    public JCheckBox getCheckbox() {
        return Checkbox;
    }

    public void setCheckbox(JCheckBox Checkbox) {
        this.Checkbox = Checkbox;
    }

    public JButton getInterrupt() {
        return Interrupt;
    }

    public void setInterrupt(JButton Interrupt) {
        this.Interrupt = Interrupt;
    }

    public JButton getRestart() {
        return Restart;
    }

    public void setRestart(JButton Restart) {
        this.Restart = Restart;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public void setjComboBox1(JComboBox<String> jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

   

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JTextField getjTextField2() {
        return jTextField2;
    }

    public void setjTextField2(JTextField jTextField2) {
        this.jTextField2 = jTextField2;
    }

    public JTextField getjTextField3() {
        return jTextField3;
    }

    public void setjTextField3(JTextField jTextField3) {
        this.jTextField3 = jTextField3;
    }

    public JTextField getjTextField4() {
        return jTextField4;
    }

    public void setjTextField4(JTextField jTextField4) {
        this.jTextField4 = jTextField4;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBarrier;
    private javax.swing.JButton ButtonIniciar;
    private javax.swing.JButton ButtonRevert;
    private javax.swing.JCheckBox Checkbox;
    private javax.swing.JButton Interrupt;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel LabelLinea;
    private javax.swing.JButton Restart;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
